/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.ExternalSensor#getPins <em>Pins</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getExternalSensor()
 * @model
 * @generated
 */
public interface ExternalSensor extends SensorType
{
  /**
   * Returns the value of the '<em><b>Pins</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pins</em>' attribute list.
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getExternalSensor_Pins()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getPins();

} // ExternalSensor
