/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mqtt Client</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.MqttClient#getBroker <em>Broker</em>}</li>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.MqttClient#getPort <em>Port</em>}</li>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.MqttClient#getClient <em>Client</em>}</li>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.MqttClient#getPub <em>Pub</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getMqttClient()
 * @model
 * @generated
 */
public interface MqttClient extends ChannelConfig
{
  /**
   * Returns the value of the '<em><b>Broker</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Broker</em>' attribute.
   * @see #setBroker(String)
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getMqttClient_Broker()
   * @model
   * @generated
   */
  String getBroker();

  /**
   * Sets the value of the '{@link org.xtext.mdsd.arduino.boardgenerator.ioT.MqttClient#getBroker <em>Broker</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Broker</em>' attribute.
   * @see #getBroker()
   * @generated
   */
  void setBroker(String value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getMqttClient_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.xtext.mdsd.arduino.boardgenerator.ioT.MqttClient#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Client</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Client</em>' attribute.
   * @see #setClient(String)
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getMqttClient_Client()
   * @model
   * @generated
   */
  String getClient();

  /**
   * Sets the value of the '{@link org.xtext.mdsd.arduino.boardgenerator.ioT.MqttClient#getClient <em>Client</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Client</em>' attribute.
   * @see #getClient()
   * @generated
   */
  void setClient(String value);

  /**
   * Returns the value of the '<em><b>Pub</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pub</em>' attribute list.
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getMqttClient_Pub()
   * @model unique="false"
   * @generated
   */
  EList<String> getPub();

} // MqttClient
