/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Onboard Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getOnboardSensor()
 * @model
 * @generated
 */
public interface OnboardSensor extends SensorType
{
} // OnboardSensor
