/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sampler</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getSampler()
 * @model
 * @generated
 */
public interface Sampler extends EObject
{
} // Sampler
