/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Output</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.SensorOutput#getSensorvar <em>Sensorvar</em>}</li>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.SensorOutput#getPipeline <em>Pipeline</em>}</li>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.SensorOutput#getChannel <em>Channel</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getSensorOutput()
 * @model
 * @generated
 */
public interface SensorOutput extends EObject
{
  /**
   * Returns the value of the '<em><b>Sensorvar</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensorvar</em>' reference.
   * @see #setSensorvar(SensorVariables)
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getSensorOutput_Sensorvar()
   * @model
   * @generated
   */
  SensorVariables getSensorvar();

  /**
   * Sets the value of the '{@link org.xtext.mdsd.arduino.boardgenerator.ioT.SensorOutput#getSensorvar <em>Sensorvar</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensorvar</em>' reference.
   * @see #getSensorvar()
   * @generated
   */
  void setSensorvar(SensorVariables value);

  /**
   * Returns the value of the '<em><b>Pipeline</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pipeline</em>' containment reference.
   * @see #setPipeline(Pipeline)
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getSensorOutput_Pipeline()
   * @model containment="true"
   * @generated
   */
  Pipeline getPipeline();

  /**
   * Sets the value of the '{@link org.xtext.mdsd.arduino.boardgenerator.ioT.SensorOutput#getPipeline <em>Pipeline</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pipeline</em>' containment reference.
   * @see #getPipeline()
   * @generated
   */
  void setPipeline(Pipeline value);

  /**
   * Returns the value of the '<em><b>Channel</b></em>' reference list.
   * The list contents are of type {@link org.xtext.mdsd.arduino.boardgenerator.ioT.Channel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel</em>' reference list.
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getSensorOutput_Channel()
   * @model
   * @generated
   */
  EList<Channel> getChannel();

} // SensorOutput
