/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.SensorType#getSensor <em>Sensor</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getSensorType()
 * @model
 * @generated
 */
public interface SensorType extends EObject
{
  /**
   * Returns the value of the '<em><b>Sensor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor</em>' attribute.
   * @see #setSensor(String)
   * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getSensorType_Sensor()
   * @model
   * @generated
   */
  String getSensor();

  /**
   * Sets the value of the '{@link org.xtext.mdsd.arduino.boardgenerator.ioT.SensorType#getSensor <em>Sensor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor</em>' attribute.
   * @see #getSensor()
   * @generated
   */
  void setSensor(String value);

} // SensorType
