/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getString()
 * @model
 * @generated
 */
public interface String extends FunctionInputType
{
} // String
