/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wifi Config</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage#getWifiConfig()
 * @model
 * @generated
 */
public interface WifiConfig extends ChannelType
{
} // WifiConfig
