/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage;
import org.xtext.mdsd.arduino.boardgenerator.ioT.Serial;
import org.xtext.mdsd.arduino.boardgenerator.ioT.StopIdentifyer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Serial</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.impl.SerialImpl#getBaud <em>Baud</em>}</li>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.impl.SerialImpl#getStopType <em>Stop Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SerialImpl extends ChannelConfigImpl implements Serial
{
  /**
   * The default value of the '{@link #getBaud() <em>Baud</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBaud()
   * @generated
   * @ordered
   */
  protected static final int BAUD_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getBaud() <em>Baud</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBaud()
   * @generated
   * @ordered
   */
  protected int baud = BAUD_EDEFAULT;

  /**
   * The cached value of the '{@link #getStopType() <em>Stop Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStopType()
   * @generated
   * @ordered
   */
  protected StopIdentifyer stopType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SerialImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IoTPackage.Literals.SERIAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getBaud()
  {
    return baud;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBaud(int newBaud)
  {
    int oldBaud = baud;
    baud = newBaud;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IoTPackage.SERIAL__BAUD, oldBaud, baud));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StopIdentifyer getStopType()
  {
    return stopType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStopType(StopIdentifyer newStopType, NotificationChain msgs)
  {
    StopIdentifyer oldStopType = stopType;
    stopType = newStopType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IoTPackage.SERIAL__STOP_TYPE, oldStopType, newStopType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStopType(StopIdentifyer newStopType)
  {
    if (newStopType != stopType)
    {
      NotificationChain msgs = null;
      if (stopType != null)
        msgs = ((InternalEObject)stopType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IoTPackage.SERIAL__STOP_TYPE, null, msgs);
      if (newStopType != null)
        msgs = ((InternalEObject)newStopType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IoTPackage.SERIAL__STOP_TYPE, null, msgs);
      msgs = basicSetStopType(newStopType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IoTPackage.SERIAL__STOP_TYPE, newStopType, newStopType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IoTPackage.SERIAL__STOP_TYPE:
        return basicSetStopType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IoTPackage.SERIAL__BAUD:
        return getBaud();
      case IoTPackage.SERIAL__STOP_TYPE:
        return getStopType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IoTPackage.SERIAL__BAUD:
        setBaud((Integer)newValue);
        return;
      case IoTPackage.SERIAL__STOP_TYPE:
        setStopType((StopIdentifyer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IoTPackage.SERIAL__BAUD:
        setBaud(BAUD_EDEFAULT);
        return;
      case IoTPackage.SERIAL__STOP_TYPE:
        setStopType((StopIdentifyer)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IoTPackage.SERIAL__BAUD:
        return baud != BAUD_EDEFAULT;
      case IoTPackage.SERIAL__STOP_TYPE:
        return stopType != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (baud: ");
    result.append(baud);
    result.append(')');
    return result.toString();
  }

} //SerialImpl
