/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage;
import org.xtext.mdsd.arduino.boardgenerator.ioT.SerialConfig;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Serial Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SerialConfigImpl extends ChannelTypeImpl implements SerialConfig
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SerialConfigImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IoTPackage.Literals.SERIAL_CONFIG;
  }

} //SerialConfigImpl
