/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage;
import org.xtext.mdsd.arduino.boardgenerator.ioT.StDev;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>St Dev</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StDevImpl extends ExecutePipelineImpl implements StDev
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StDevImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IoTPackage.Literals.ST_DEV;
  }

} //StDevImpl
