/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ioT.impl;

import java.lang.String;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.mdsd.arduino.boardgenerator.ioT.IoTPackage;
import org.xtext.mdsd.arduino.boardgenerator.ioT.Wifi;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Wifi</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.impl.WifiImpl#getSsid <em>Ssid</em>}</li>
 *   <li>{@link org.xtext.mdsd.arduino.boardgenerator.ioT.impl.WifiImpl#getPass <em>Pass</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WifiImpl extends ChannelConfigImpl implements Wifi
{
  /**
   * The default value of the '{@link #getSsid() <em>Ssid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSsid()
   * @generated
   * @ordered
   */
  protected static final String SSID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSsid() <em>Ssid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSsid()
   * @generated
   * @ordered
   */
  protected String ssid = SSID_EDEFAULT;

  /**
   * The default value of the '{@link #getPass() <em>Pass</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPass()
   * @generated
   * @ordered
   */
  protected static final String PASS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPass() <em>Pass</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPass()
   * @generated
   * @ordered
   */
  protected String pass = PASS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WifiImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IoTPackage.Literals.WIFI;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSsid()
  {
    return ssid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSsid(String newSsid)
  {
    String oldSsid = ssid;
    ssid = newSsid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IoTPackage.WIFI__SSID, oldSsid, ssid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPass()
  {
    return pass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPass(String newPass)
  {
    String oldPass = pass;
    pass = newPass;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IoTPackage.WIFI__PASS, oldPass, pass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IoTPackage.WIFI__SSID:
        return getSsid();
      case IoTPackage.WIFI__PASS:
        return getPass();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IoTPackage.WIFI__SSID:
        setSsid((String)newValue);
        return;
      case IoTPackage.WIFI__PASS:
        setPass((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IoTPackage.WIFI__SSID:
        setSsid(SSID_EDEFAULT);
        return;
      case IoTPackage.WIFI__PASS:
        setPass(PASS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IoTPackage.WIFI__SSID:
        return SSID_EDEFAULT == null ? ssid != null : !SSID_EDEFAULT.equals(ssid);
      case IoTPackage.WIFI__PASS:
        return PASS_EDEFAULT == null ? pass != null : !PASS_EDEFAULT.equals(pass);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ssid: ");
    result.append(ssid);
    result.append(", pass: ");
    result.append(pass);
    result.append(')');
    return result.toString();
  }

} //WifiImpl
