/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.scoping;

import org.xtext.mdsd.arduino.boardgenerator.scoping.AbstractIoTScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class IoTScopeProvider extends AbstractIoTScopeProvider {
}
