/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mdsd.arduino.boardgenerator.IoTRuntimeModule;
import org.xtext.mdsd.arduino.boardgenerator.IoTStandaloneSetup;
import org.xtext.mdsd.arduino.boardgenerator.ide.IoTIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class IoTIdeSetup extends IoTStandaloneSetup {
  @Override
  public Injector createInjector() {
    IoTRuntimeModule _ioTRuntimeModule = new IoTRuntimeModule();
    IoTIdeModule _ioTIdeModule = new IoTIdeModule();
    return Guice.createInjector(Modules2.mixin(_ioTRuntimeModule, _ioTIdeModule));
  }
}
