/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mdsd.arduino.boardgenerator;

import org.xtext.mdsd.arduino.boardgenerator.IoTStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IoTStandaloneSetup extends IoTStandaloneSetupGenerated {
  public static void doSetup() {
    new IoTStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
